version: "3"
services:
    backend:
        build: ./backend
        ports:
            - "3001:3001"
        depends_on:
            - mysql
        environment:
            - DB_HOST=mysql
            - DB_USER=root
            - DB_PASSWORD=root
            - DB_NAME=Bank3
            - DB_PORT=3306
        volumes:
            - ./backend/.env:/app/.env # Mount the .env file

    frontend:
        build: ./frontend
        ports:
            - "3000:3000"
        depends_on:
            - backend

    mysql:
        image: mysql:5.7
        platform: linux/amd64
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: Bank3
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql

volumes:
    mysql-data:
